sudo: false
language: node_js
node_js:
- 0.10
- 0.12
- 4
- node
matrix:
  include:
  - node_js: node
    env: TEST_BROWSERS=true
script: npm run ci
deploy:
  provider: npm
  email: mike@cousins.io
  api_key:
    secure: FUoEPzk+yeDesK2XTrggLrSFDrA4yvaxJDoJ/IP5OTU2STQq9cOb8kGH5RXV+OO6U+zSBPpW7THQjkGW9FB9wry5o5XWnnbOM9GORlun5zrB2iXRJF+pH9TfLPjVGRW85xPibi7+thYFINqqKTccs+uSLMWwQB5E/eySpKxeyLf6YCN7TUBERLLdJvUt2f9Nuhph3paLJwubZFTniWHVn/YshOyu2XvoDHv3xj2VwKonQAWG4/c2tIRWTwSmiefTjC7cWonZz8Je04aIgGzlzmCYR3v8tYL/63BQ6OPi+VutisSaEIMlnrDnU8rZiGPg3L5Sy0NYbh2K+xuKNEFdz/ZHevBzFfsB0bmXLznOkEFtsy2CXuczoOTIYbMMxljohBWySlXdcdx25oYIcchy7Rj8hl8RqQUzO0BdlOFwWFXINfikFjETcnMMU4Oe6aUdc1jyANPBZJk1+KE2s768vO8xHC76DUXE43VFXPTBCOL/OmRhsA70Oj5zDUGVovZ5zQSZgdxjV1xAst/bj+ZpoYTtgUnSHOLDHAzaB3SyGg/ZSviocp2B3CydOG9nTp8Y0ZKWX1MD+/DrfQH7MfCh0gZylCh18tB1aDj6hdIE2TasUdjrjgjpcB07ue8/scDKfJnuFADBpRVALeIL1mzuSL9lmHDyeqj2UKGZ/pbNdwU=
  on:
    node: node
    tags: true
    all_branches: true
    condition: $TEST_BROWSERS = true
    repo: mcous/xmlovely
env:
  global:
  - secure: P7KuSHYaW3wyliXaRKwvAzNBnhdQPf1PRzhJtH0XfvO4C5ypLhpcNhrv2fMWXlHmnCVD4RLb/r2s3+z2V6BFdCu70o5okiC8zebIzrg5nalYrXv5iGiHiuFEgAaKhYDjgxYCef11yg7wo3LRLM/KTrVNcH7idX5u05t8hJ99DD1gKOdxA6nvRIWuBtx5CMGW1RJDbJmvAJ5O8EzCTie9rtjwCHl0VGJ5Hzs5muJkRaTdZNxnkYeKHhcXfNvvMZb+8p2fWdQYXiUDs/eGamRTxW0zbb3cNSW49kUVuU11E/lXzrOvPS56b/Kvgt8wZzU8ovlGRZCSDFKbK5cOwC8rHxkqMi88JQD0vnZmxkS+LKM9vb7vc0GMGjSbbT2vgoemg3HK+xRO6l4pYQ/XKiIFj5GbWWz6KllZmupwH9uaaMOvPx6f+1JNA66u2h9wJJKO9lwKvxzR7cTb1ZRlja1d9w54RQLSErF1nNjYReZ8Llx7cPolFJ9mRALwhfG5LkDVje1r3ZVLY7eddvD+77SwRzDyLgja5Xxzbqm+GLKHJ68A/frX4KGlCh7hKsLU/qUB1JKbhc5j+GG5lon+7jCcMhQ0eD9jBaOaz8QZfVbdHmsbPkWEFRmJDx4QpeBRhO9qLyEN12+P/Dro75CmsQNIrJ0YZBBIE/ZWKW6c20u4/GQ=
  - secure: tTcWw5qNHHR7N2mFU6nIvtEZ8IcBK2rZFZRXktvWzh8uh5ftliuKgXHq8KoFJU6jbc3F/kp53z361/qgOhSPJTVKrgEfU7Ew3RX6WdjqRnm9AINNiL67UZkceOadvo9AaZCfNbWfT49pUtL5H5b/0JQZnGFSBc3Avb9cM9NPW0ZzjvSGkvzVCreARLTV3XNvIbayxOP0DKE1FHvn3MueXFGrZ/ajNH36//rYFWJhRK99n50R4yYCidEA4Uxo+Tf26kGv57Z3oIosXBMvsDAUAOILkmYTWReHHYVne7z+VcnD6UDzcYKIdphOwabN4EvMTotFpJLK9crCAuTZGPDtFOaXP9ZbhoZNBfchMkXYMOvce+8gVY0PjaLIrZmoN2SpB9Px3jr+7CQbdwUJTpp02iEHzwoUtKwhdZVmyfuqHdCR9x/J1SPJ3Au10gXLGplB2Ldz2K2eoJ4+rVk2QkOdFS+lxLYd6SysAXPFQWQ4fWzsZ8N+A5Y549klv1mmSFp2D6fMtoTrlUsdKkBleVx4DPQmbDlSc3gAcu6S0lDCMKPPFvnWXKSHCzl4y06TDYQf+cZzd8aNM2S5n61HBomb5R9IpPq9njVWvrnTV7HqY/ugFKSFvag1o6ml4yn/VObkxlePbj2Hq/7cu3+VZe5EK22jwbpSFhUj1os4pD1Y6vI=
